highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /Joie-Resume-/
title: Joie Nhu Nguyen's Resume
name: Nhu Nguyen 
email: nhunguyen.ja@gmail.com
email_full: 
website: 
website_full: 
github: trending
twitter: twitter
tel: +84 944118811
tel_full: tel:+840000000000
google_maps: 
address:
  street: Nguyen Van Troi Street
  postcode: 7000000
  city: Ho Chi Minh
  country: Vietnam
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
